/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as _authRouteImport } from './routes/__auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _authWatchListRouteImport } from './routes/__auth/watchList'
import { Route as _authHomeRouteImport } from './routes/__auth/home'
import { Route as _authExploreRouteImport } from './routes/__auth/explore'
import { Route as _authPeoplePersonIdRouteImport } from './routes/__auth/people/$personId'
import { Route as _authMoviesTrendingRouteImport } from './routes/__auth/movies/trending'
import { Route as _authMoviesPopularRouteImport } from './routes/__auth/movies/popular'
import { Route as _authMoviesMovieIdRouteImport } from './routes/__auth/movies/$movieId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRoute = _authRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _authWatchListRoute = _authWatchListRouteImport.update({
  id: '/watchList',
  path: '/watchList',
  getParentRoute: () => _authRoute,
} as any)
const _authHomeRoute = _authHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _authRoute,
} as any)
const _authExploreRoute = _authExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => _authRoute,
} as any)
const _authPeoplePersonIdRoute = _authPeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => _authRoute,
} as any)
const _authMoviesTrendingRoute = _authMoviesTrendingRouteImport.update({
  id: '/movies/trending',
  path: '/movies/trending',
  getParentRoute: () => _authRoute,
} as any)
const _authMoviesPopularRoute = _authMoviesPopularRouteImport.update({
  id: '/movies/popular',
  path: '/movies/popular',
  getParentRoute: () => _authRoute,
} as any)
const _authMoviesMovieIdRoute = _authMoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => _authRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/explore': typeof _authExploreRoute
  '/home': typeof _authHomeRoute
  '/watchList': typeof _authWatchListRoute
  '/movies/$movieId': typeof _authMoviesMovieIdRoute
  '/movies/popular': typeof _authMoviesPopularRoute
  '/movies/trending': typeof _authMoviesTrendingRoute
  '/people/$personId': typeof _authPeoplePersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/explore': typeof _authExploreRoute
  '/home': typeof _authHomeRoute
  '/watchList': typeof _authWatchListRoute
  '/movies/$movieId': typeof _authMoviesMovieIdRoute
  '/movies/popular': typeof _authMoviesPopularRoute
  '/movies/trending': typeof _authMoviesTrendingRoute
  '/people/$personId': typeof _authPeoplePersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__auth': typeof _authRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/__auth/explore': typeof _authExploreRoute
  '/__auth/home': typeof _authHomeRoute
  '/__auth/watchList': typeof _authWatchListRoute
  '/__auth/movies/$movieId': typeof _authMoviesMovieIdRoute
  '/__auth/movies/popular': typeof _authMoviesPopularRoute
  '/__auth/movies/trending': typeof _authMoviesTrendingRoute
  '/__auth/people/$personId': typeof _authPeoplePersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/explore'
    | '/home'
    | '/watchList'
    | '/movies/$movieId'
    | '/movies/popular'
    | '/movies/trending'
    | '/people/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/explore'
    | '/home'
    | '/watchList'
    | '/movies/$movieId'
    | '/movies/popular'
    | '/movies/trending'
    | '/people/$personId'
  id:
    | '__root__'
    | '/'
    | '/__auth'
    | '/about'
    | '/login'
    | '/__auth/explore'
    | '/__auth/home'
    | '/__auth/watchList'
    | '/__auth/movies/$movieId'
    | '/__auth/movies/popular'
    | '/__auth/movies/trending'
    | '/__auth/people/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authRoute: typeof _authRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/watchList': {
      id: '/__auth/watchList'
      path: '/watchList'
      fullPath: '/watchList'
      preLoaderRoute: typeof _authWatchListRouteImport
      parentRoute: typeof _authRoute
    }
    '/__auth/home': {
      id: '/__auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof _authHomeRouteImport
      parentRoute: typeof _authRoute
    }
    '/__auth/explore': {
      id: '/__auth/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof _authExploreRouteImport
      parentRoute: typeof _authRoute
    }
    '/__auth/people/$personId': {
      id: '/__auth/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof _authPeoplePersonIdRouteImport
      parentRoute: typeof _authRoute
    }
    '/__auth/movies/trending': {
      id: '/__auth/movies/trending'
      path: '/movies/trending'
      fullPath: '/movies/trending'
      preLoaderRoute: typeof _authMoviesTrendingRouteImport
      parentRoute: typeof _authRoute
    }
    '/__auth/movies/popular': {
      id: '/__auth/movies/popular'
      path: '/movies/popular'
      fullPath: '/movies/popular'
      preLoaderRoute: typeof _authMoviesPopularRouteImport
      parentRoute: typeof _authRoute
    }
    '/__auth/movies/$movieId': {
      id: '/__auth/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof _authMoviesMovieIdRouteImport
      parentRoute: typeof _authRoute
    }
  }
}

interface _authRouteChildren {
  _authExploreRoute: typeof _authExploreRoute
  _authHomeRoute: typeof _authHomeRoute
  _authWatchListRoute: typeof _authWatchListRoute
  _authMoviesMovieIdRoute: typeof _authMoviesMovieIdRoute
  _authMoviesPopularRoute: typeof _authMoviesPopularRoute
  _authMoviesTrendingRoute: typeof _authMoviesTrendingRoute
  _authPeoplePersonIdRoute: typeof _authPeoplePersonIdRoute
}

const _authRouteChildren: _authRouteChildren = {
  _authExploreRoute: _authExploreRoute,
  _authHomeRoute: _authHomeRoute,
  _authWatchListRoute: _authWatchListRoute,
  _authMoviesMovieIdRoute: _authMoviesMovieIdRoute,
  _authMoviesPopularRoute: _authMoviesPopularRoute,
  _authMoviesTrendingRoute: _authMoviesTrendingRoute,
  _authPeoplePersonIdRoute: _authPeoplePersonIdRoute,
}

const _authRouteWithChildren = _authRoute._addFileChildren(_authRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authRoute: _authRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
